name: 'Diary Emotion Status'
description: 'Updates GitHub status based on emotions detected from Notion diary entries'
author: 'your-github-username'

branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  notion_token:
    description: 'Notion API integration token'
    required: true
  notion_database_id:
    description: 'Notion diary database ID'
    required: true
  github_token:
    description: 'GitHub token with user scope'
    required: true
  entries_limit:
    description: 'Number of recent diary entries to analyze'
    required: false
    default: '10'
  model_name:
    description: 'Emotion analysis model name'
    required: false
    default: 'circulus/koelectra-emotion-v1'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false

    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction --no-root

    - name: Update GitHub Status
      shell: bash
      env:
        NOTION_TOKEN: ${{ inputs.notion_token }}
        NOTION_DATABASE_ID: ${{ inputs.notion_database_id }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ENTRIES_LIMIT: ${{ inputs.entries_limit }}
        MODEL_NAME: ${{ inputs.model_name }}
      run: poetry run python -c "import asyncio; from diary_emotion_action.main import main; asyncio.run(main())"
